<?php
    /** @var Magento\Framework\View\Element\Template\ $block */
    /** @var Magento\Framework\Escaper $escaper */
    /** @var Macademy\Blog\ViewModel\Post $postVm */
    $postVm = $block->getData('post_vm');

?>

<div class="blog-post-list">

    <h1><?= __('Blog Posts')?></h1>

    <ul class="blog-post-list">
        <?php foreach ($postVm->getList() as $post): ?>
        <li class="blog-post">
            <a href="<?= $block->getUrl('blog/post/detail', ['id' => $post->getData('id')]) ?>">
                <?= $escaper->escapeHtml($post->getData('title')) ?>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>

    <p class="blog-post-counter-label"><?= __('Post Count: %1', $postVm->getCount())?></p>
</div>


